### ISSUE TITLE
TypeError when resolving local platforms.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1043]
As seen in https://github.com/pantsbuild/example-python CI:
```
raceback (most recent call last):
  File "/home/travis/.pex/unzipped_pexes/49b4b32295a60a0a4dfc0659c3a44f93560c4a81/.bootstrap/pex/pex.py", line 423, in execute
    exit_code = self._wrap_coverage(self._wrap_profiling, self._execute)
  File "/home/travis/.pex/unzipped_pexes/49b4b32295a60a0a4dfc0659c3a44f93560c4a81/.bootstrap/pex/pex.py", line 356, in _wrap_coverage
    return runner(*args)
  File "/home/travis/.pex/unzipped_pexes/49b4b32295a60a0a4dfc0659c3a44f93560c4a81/.bootstrap/pex/pex.py", line 387, in _wrap_profiling
    return runner(*args)
  File "/home/travis/.pex/unzipped_pexes/49b4b32295a60a0a4dfc0659c3a44f93560c4a81/.bootstrap/pex/pex.py", line 474, in _execute
    return self.execute_entry(self._pex_info.entry_point)
  File "/home/travis/.pex/unzipped_pexes/49b4b32295a60a0a4dfc0659c3a44f93560c4a81/.bootstrap/pex/pex.py", line 576, in execute_entry
    return runner(entry_point)
  File "/home/travis/.pex/unzipped_pexes/49b4b32295a60a0a4dfc0659c3a44f93560c4a81/.bootstrap/pex/pex.py", line 592, in execute_pkg_resources
    return runner()
  File "/home/travis/.pex/unzipped_pexes/49b4b32295a60a0a4dfc0659c3a44f93560c4a81/.deps/pex-2.1.16-py2.py3-none-any.whl/pex/bin/pex.py", line 970, in main
    pex_builder = build_pex(reqs, options, cache=ENV.PEX_ROOT)
  File "/home/travis/.pex/unzipped_pexes/49b4b32295a60a0a4dfc0659c3a44f93560c4a81/.deps/pex-2.1.16-py2.py3-none-any.whl/pex/bin/pex.py", line 762, in build_pex
    resolved_platforms = candidate_interpreter.supported_platforms.intersection(
AttributeError: 'tuple' object has no attribute 'supported_platforms'
```

**Comment by jsirois** [comment]
This was introduced in #1028 here: https://github.com/pantsbuild/pex/pull/1028#discussion_r495193476
